name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"
inputs:
  rust-cache:
    description: "which cache to use for Rust"
    required: false
    default: "github"

runs:
  using: "composite"
  steps:
    - name: Install stable
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.85.1
        components: rustc, rustfmt, rust-std, clippy, rustc-dev, rust-docs

    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        cache-on-failure: true
        cache-provider: ${{ inputs.rust-cache }}
        workspaces: |
          .

    # we rely on foundry for some specific tests
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.0.0

    - name: Run Forge build
      shell: bash
      run: |
        cd evm-contracts
        forge --version
        forge build --sizes
      id: build

    - name: Install Solana
      shell: bash
      run: |
        curl -sSfL https://release.anza.xyz/v2.2.14/install | sh
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Install needed tooling (needed for solana deps)
      shell: bash
      run: |
        sudo apt-get install -y protobuf-compiler bzip2 clang

    - name: Install deps for rust check and docs
      shell: bash
      run: |
        sudo apt-get install -y pkg-config libusb-1.0-0-dev libftdi1-dev
        sudo apt-get install -y libudev-dev
