//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[sea_orm(rs_type = "String", db_type = "String(None)")]
#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq)]
pub enum Chain {
    #[sea_orm(string_value = "axelar")]
    Axelar,
    #[sea_orm(string_value = "solana")]
    Solana,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "last_processed_block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub height: u64,
    pub chain: Chain,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
