name: Setup Stellar CLI & Network
description: Install Stellar CLI and starts local Stellar network

runs:
    using: 'composite'
    steps:
        - name: Install Stellar CLI
          shell: bash
          run: cargo install --locked stellar-cli --version 22.2.0 --features opt

        - name: Start Stellar local network
          shell: bash
          run: |
              stellar container start local --protocol-version 22
              echo "rpc_url=http://localhost:8000/soroban/rpc" >> $GITHUB_ENV
              echo "network_passphrase=Standalone Network ; February 2017" >> $GITHUB_ENV

        - name: Wait for Stellar network
          shell: bash
          run: |
              echo "Waiting for Stellar network to be reachable (rpc + friendbot)..."
              for i in {1..60}; do
                echo "Attempt $i: checking..."
                if ! curl -s http://localhost:8000/ | grep -q '"current_protocol_version"'; then
                  echo "  - RPC not ready yet"
                  sleep 2
                  continue
                fi
                if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/friendbot | grep -q '^[0-9][0-9][0-9]$'; then
                  echo "✅ Stellar network is ready"
                  exit 0
                else
                  echo "  - Friendbot not responding (curl failure)"
                fi
                sleep 2
              done
              echo "❌ Stellar network did not become ready in 120 seconds."
              exit 1

        - name: Add as configured network
          shell: bash
          run: |
              stellar network add local \
                --rpc-url "$rpc_url" \
                --network-passphrase "$network_passphrase"

        - name: Retrieve native token address
          shell: bash
          run: |
              echo "xlm_address=$(stellar contract id asset --asset native --network local)" >> $GITHUB_ENV
