name: Setup Stellar CLI & Network
description: Install Stellar CLI and start a local Stellar network

runs:
    using: 'composite'
    env:
        HORIZON_RPC: 'http://localhost:8000'
        RPC_URL: 'http://localhost:8000/soroban/rpc'
        NETWORK_PASSPHRASE: 'Standalone Network ; February 2017'
    steps:
        - name: Install stable Rust toolchain
          uses: dtolnay/rust-toolchain@stable

        - name: Install Stellar CLI
          shell: bash
          run: cargo install --locked stellar-cli --version 22.2.0 --features opt

        - name: Start Stellar local network
          id: start
          shell: bash
          run: |
              stellar container start local --protocol-version 22
              echo "horizon_rpc=${HORIZON_RPC}" >> "$GITHUB_OUTPUT"
              echo "rpc_url=${RPC_URL}" >> "$GITHUB_OUTPUT"
              echo "network_passphrase=${NETWORK_PASSPHRASE}" >> "$GITHUB_OUTPUT"

        - name: Wait for Stellar network
          shell: bash
          run: |
              echo "Waiting for Stellar network RPC to become ready..."
              while true; do
                echo "Checking..."
                if curl -s "${HORIZON_RPC}/" | grep -q '"current_protocol_version"'; then
                  echo "✅ Stellar RPC is ready"
                  exit 0
                fi
                echo "  - RPC not ready yet"
                sleep 2
              done

        - name: Add as configured network
          shell: bash
          run: |
              stellar network add local \
                --rpc-url "${RPC_URL}" \
                --network-passphrase "${NETWORK_PASSPHRASE}"

        - name: Retrieve native token address
          id: native_token
          shell: bash
          run: |
              echo "xlm_address=$(stellar contract id asset --asset native --network local)" >> "$GITHUB_OUTPUT"
