name: Setup Stellar CLI & Network
description: Install Stellar CLI and start a local Stellar network

runs:
    using: 'composite'
    steps:
        - name: Install stable Rust toolchain
          uses: dtolnay/rust-toolchain@stable

        - name: Install Stellar CLI
          shell: bash
          run: cargo install --locked stellar-cli --version 22.2.0 --features opt

        - name: Set environment variables
          shell: bash
          run: |
              echo "NETWORK_PASSPHRASE='Standalone Network ; February 2017'" >> $GITHUB_ENV
              echo "LOCALHOST=http://localhost:8000" >> $GITHUB_ENV
              echo "HORIZON_RPC=$LOCALHOST" >> $GITHUB_ENV
              echo "SOROBAN_RPC=$LOCALHOST/soroban/rpc" >> $GITHUB_ENV
              echo "FRIENDBOT=$LOCALHOST/friendbot" >> $GITHUB_ENV

        - name: Start Stellar local network
          shell: bash
          run: |
              stellar container start local --protocol-version 22

        - name: Wait for Stellar network
          shell: bash
          run: |
              echo "Waiting for Stellar network to become ready..."
              until curl -s "$FRIENDBOT" | grep -q '"status"'; do
                echo "  - Stellar Network not ready yet"
                sleep 2
              done
              echo "✅ Stellar Network is ready"

        - name: Add as configured network
          shell: bash
          run: |
              stellar network add local \
                --rpc-url "$SOROBAN_RPC" \
                --network-passphrase "$NETWORK_PASSPHRASE"

        - name: Prepare local.json
          shell: bash
          run: |
              echo '{
                  "chains": {
                      "stellar": {
                          "name": "Stellar",
                          "axelarId": "stellar",
                          "networkType": "local",
                          "chainType": "stellar",
                          "tokenSymbol": "XLM",
                          "tokenAddress": "CDMLFMKMMD7MWZP3FKUBZPVHTUEDLSX4BYGYKH4GCESXYHS3IHQ4EIG4",
                          "rpc": "$SOROBAN_RPC",
                          "horizonRpc": "$HORIZON_RPC",
                          "contracts": {}
                      }
                  }
              }' > ./axelar-chains-config/info/local.json

        - name: Display local.json
          shell: bash
          run: cat ./axelar-chains-config/info/local.json

        - name: Prepare .env
          shell: bash
          run: |
              ROOT_SECRET=$(stellar container logs local | grep 'network root secret key:' | cut -d ':' -f2 | xargs)
              echo "PRIVATE_KEY=$ROOT_SECRET" >> .env
              echo "ENV=local" >> .env
              echo "CHAIN=stellar" >> .env
              echo "YES=true" >> .env
