name: Update config

on:
  pull_request_target:
    types: [closed]

jobs:
  reusable-update-config:
    if: github.event.pull_request.merged == true
    uses: .github/workflows/reusable-update-config.yaml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHAINS_REPO_CICD_TOKEN: ${{ secrets.CHAINS_REPO_CICD_TOKEN }}
      CONFIG_REPO: ${{ secrets.CONFIG_REPO }}
