name: Linting

on: pull_request

jobs:
  lint:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo Following files are changed by prettier...
            git status

            echo Changes:
            git diff

            exit 1;
          else
            exit 0;
          fi
