name: Unit Tests

on: pull_request

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  chains-config-tests:
    name: Run Axelar Chains Config Tests
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install
        run: npm ci
        working-directory: axelar-chains-config

      - name: Build
        run: npm run build
        working-directory: axelar-chains-config

      - name: Test axelar-chains-config
        run: npm run test
        working-directory: axelar-chains-config
